#!/usr/bin/env python

import argparse
import subprocess

""" 
Prerequisites
    `svn`

Final command should look like
    svn export https://github.com/numpy/numpy.git/trunk/tools tools

Input should look like
    https://github.com/numpy/numpy/tree/master/tools

Todo
    - adapt for gitlab, ... 
    - use custom output directory name
"""


def with_slashes(*args):
    """ 
    Example
    -------
    with_slashes("wtf", "ww", "ok") results in 'wtf/ww/ok/'.
    """
    s = ""
    for i in args:
        s += i + "/"
    return s

parser = argparse.ArgumentParser(description='Download subdirectory from' + \
        'github repository.')

parser.add_argument('link', type = str, nargs = 1)

args = parser.parse_args()

link = args.link[0]

# split into ['https:', 'github.com/numpy/numpy/tree/master/tools']
link_1 = link.split("//")

# split into ['github.com', 'numpy', 'numpy', 'tree', 'master', 'tools']
link_11 = link_1[1].split("/")

link_final = link_1[0] + "//" + with_slashes(*link_11[:3]) + "trunk/" + \
        with_slashes(*link_11[5:])

print(link_final)

subprocess.call(['svn', 'export', link_final])
